### PR TITLE
minor changes to allow API integration

### PR DESCRIPTION
**Pull request by cwjackso**
I tried integrating your latest build with the Feefo API and had some issues with the "Date" property coming back as a string formatted as "XX minutes ago" rather than a valid DateTime.

I also had issues with the "ProductRating" property coming back as an empty string rather than something convertible to the Rating enum.

This pr is a fix for these issues.

### CODE REVIEW

**Comment by kevbite** [comment]
Would be nice if we could try keep the Date type safe and use a converter to convert "XX minutes ago" to a relative date. Do you have an example of a supplier or response from feefo that returns this? Thanks

**Comment by kevbite** [comment]
Also I think you've missed out changing the mocked resource as I'm getting the following error while running the tests:

```
  Expected string length 14 but was 11. Strings differ at index 0.
  Expected: "56 minutes ago"
  But was:  "10-Sep-2015"
  -----------^

   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Feefo.Tests.FeefoClientTests.ThenTheFeedbackIsCorrect() in FeefoClientTests.cs: line 85

```

**Comment by cwjackso** [comment]
I'll have a look as I have had to modify quite a few things to make the project work correctly with the feed we are using.

I made some changes to the tests but must have missed the mocks.

**Comment by cwjackso** [comment]
The feed we have used is from www.hitachipersonalfinance.co.uk BTW

**Comment by kevbite** [comment]
Ill give this a go later tonight.

**Comment by kevbite** [comment]
Got this replicating easily by using the supplied logon, Its a shame Feefo don't stick to their defined structures as explained in their integration document says: 
http://www.feefo.com/documentation/feefo_integration.pdf

```
<DATE />
The date that this feedback was left, in the format dd-MMM-yyyy , eg. “01-Jan-2013”
```

**Comment by kevbite** [comment]
@cwjackso I've updated the master to reflect what you're seeing within your feefo feed so version 2.0.0  should work for your feed, can you test this out?

**Pull request closed without merging**
